### ISSUE TITLE
the whole page gets deleted while undo-ing 

### ISSUE THREAD

**Issue by HusainAmir** [BlupGithub/Blup-IDE#6] opened 2023-09-01 06:33 UTC
When we create a new page and then draw a rectangle in it. Then if you undo it with ctrl+z, it removes the whole page that was created.

**Comment by HusainAmir** [comment] 2023-09-01 06:34
@ashutosh2014 fix it asap.

**Comment by ashutosh2014** [comment] 2023-09-08 11:41
Hi @HusainAmir, Thanks for reporting the issue, the issue is fixed now, and you will receive in 1.09 update.

**Closed as completed by ashutosh2014** 2023-09-08 11:41 UTC
